export const DELETE_ALL_SHAPES = "DELETE_ALL_SHAPES";
export const DELETE_ALL_OF_SHAPE_TYPE = "DELETE_ALL_OF_SHAPE_TYPE";
export const DECREASE_SHAPE_QUANTITY_BY_ONE = "DECREASE_SHAPE_QUANTITY_BY_ONE";
export const INCREASE_SHAPE_QUANTITY_BY_ONE = "INCREASE_SHAPE_QUANTITY_BY_ONE";
export const ADD_RANDOM_SHAPE = "ADD_RANDOM_SHAPE";
export const SHUFFLE_SHAPES = "SHUFFLE_SHAPES";
